/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Simbok_pc
 */
public class CobaLai extends javax.swing.JFrame {

    /**
     * Creates new form CobaLai
     */
    public CobaLai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopFile = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Perkalian = new javax.swing.JMenuItem();
        Pemangkatan = new javax.swing.JMenuItem();
        Faktorial = new javax.swing.JMenuItem();
        Permutasi = new javax.swing.JMenuItem();
        Kombinasi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopFileLayout = new javax.swing.GroupLayout(desktopFile);
        desktopFile.setLayout(desktopFileLayout);
        desktopFileLayout.setHorizontalGroup(
            desktopFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopFileLayout.setVerticalGroup(
            desktopFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        Perkalian.setText("Perkalian");
        Perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerkalianActionPerformed(evt);
            }
        });
        jMenu1.add(Perkalian);

        Pemangkatan.setText("Pemangkatan");
        Pemangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemangkatanActionPerformed(evt);
            }
        });
        jMenu1.add(Pemangkatan);

        Faktorial.setText("Faktorial");
        Faktorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaktorialActionPerformed(evt);
            }
        });
        jMenu1.add(Faktorial);

        Permutasi.setText("Permutasi");
        Permutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermutasiActionPerformed(evt);
            }
        });
        jMenu1.add(Permutasi);

        Kombinasi.setText("Kombinasi");
        Kombinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KombinasiActionPerformed(evt);
            }
        });
        jMenu1.add(Kombinasi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopFile)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopFile)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerkalianActionPerformed
        Perkalian perkalian = new Perkalian();
        perkalian.show();
        desktopFile.add(perkalian);
    }//GEN-LAST:event_PerkalianActionPerformed

    private void FaktorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaktorialActionPerformed
        Faktorial faktorial = new Faktorial();
        faktorial.show();
        desktopFile.add(faktorial);
    }//GEN-LAST:event_FaktorialActionPerformed

    private void PermutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermutasiActionPerformed
        Permutasi permutasi = new Permutasi();
        permutasi.show();
        desktopFile.add(permutasi);
    }//GEN-LAST:event_PermutasiActionPerformed

    private void KombinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KombinasiActionPerformed
        Kombinasi kombinasi = new Kombinasi();
        kombinasi.show();
        desktopFile.add(kombinasi);
    }//GEN-LAST:event_KombinasiActionPerformed

    private void PemangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemangkatanActionPerformed
        Pemangkatan pemangkatan = new Pemangkatan();
        pemangkatan.show();
        desktopFile.add(pemangkatan);
    }//GEN-LAST:event_PemangkatanActionPerformed

                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobaLai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobaLai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobaLai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobaLai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CobaLai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Faktorial;
    private javax.swing.JMenuItem Kombinasi;
    private javax.swing.JMenuItem Pemangkatan;
    private javax.swing.JMenuItem Perkalian;
    private javax.swing.JMenuItem Permutasi;
    private javax.swing.JDesktopPane desktopFile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
